apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: qa
namePrefix: qa-
resources:
- ../../base
#components:
#  - ../../variants/prod
patches:
- path: simple-app-go.yaml
#- path: simple-app-go-version.yaml
#- path: simple-app-go-settings.yaml

images:
- name: ghcr.io/djimenezc/devops-automation/simple-app-go
  newTag: 2.0.1
