apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-go
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: simple-app-go=ghcr.io/djimenezc/devops-automation/simple-app-go:^2.0
    argocd-image-updater.argoproj.io/psplusext.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater/git-creds
    argocd-image-updater.argoproj.io/write-back-target: "kustomization:/environments/promotion-helm-kustomize/envs/qa"
spec:
  destination:
    namespace: qa
  sources:
    - chart: helm-simple-go-app
      targetRevision: 0.1.0
      repoURL: ghcr.io/djimenezc
      helm:
        valueFiles:
          - $values/environments/promotion-helm-kustomize/envs/qa/simple-app-go-settings.yaml
          - $values/environments/promotion-helm-kustomize/envs/qa/simple-app-go-version.yaml
    - repoURL: 'https://github.com/djimenezc/devops-automation'
      ref: values
      targetRevision: feature/environment-promotion

