ansible_connection: ssh
ansible_ssh_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/david-key.pem

security_scanner_dependencies_ubuntu:
  - software-properties-common
  - git
  - vim
  - curl
  - ca-certificates
  - gnupg
  - lsb-release
  - python3
  - python3-pip
  - awscli
  - jq
  - telnet
  - tmux
  - qemu
  - binfmt-support
  - qemu-user-static
#  - podman

#  - openssl-devel
#  - perl
#  - perl-Net-SSLeay
#  - perl-Crypt-SSLeay

security_scanner_dependencies_amazon_linux_2:
  - git
  - vim
  - docker
  - jq
  - telnet
  - tmux
  - openssl-devel
  - perl
  - perl-Net-SSLeay
  - perl-Crypt-SSLeay
