apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-go
  namespace: argocd
spec:
  destination:
    namespace:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: helm-simple-go-app
      targetRevision: 0.1.0
      helm:
        releaseName: helm-simple-go-app
        valueFiles:
          - $values/environments/promotion-helm/base/simple-app-go-values.yaml
          - $values/environments/promotion-helm/base/simple-app-go-version.yaml
    - repoURL: 'https://github.com/djimenezc/devops-automation'
      ref: values
      targetRevision: feature/environment-promotion
