apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-go
  namespace: argocd
spec:
  destination:
    namespace:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    chart: helm-simple-go-app
    repoURL: ghcr.io/djimenezc
    targetRevision: ^0.1.0
    helm:
      releaseName: simple-app-go
      passCredentials: true
      valueFiles:
        - simple-app-go-version.yaml
