---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        image: ghcr.io/djimenezc/devops-automation/simple-app-go:1.0
