apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-go
  namespace: argocd
spec:
  destination:
    namespace: staging
    name: in-cluster
  project: default
  source:
    repoURL: git@github.com:djimenezc/devops-automation.git
    targetRevision: feature/environment-promotion
  sources:
    - chart: helm-simple-go-app
      targetRevision: 0.1.0
      repoURL: ghcr.io/djimenezc
      helm:
        valueFiles:
          - $values/environments/promotion-helm/envs/staging/values.yaml
          - $values/environments/promotion-helm/envs/staging/version.yaml
    - repoURL: 'https://github.com/djimenezc/devops-automation'
      ref: values
      targetRevision: feature/environment-promotion

