version: "3.8"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD:
    restart: always
    networks:
      - capi
    ports:
      - 8081:80

  # https://hub.docker.com/r/rediscommander/redis-commander
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    depends_on:
      redis:
        condition: service_healthy
    restart: always

    networks:
      - capi
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"


networks:
  capi:
    name: capi
