apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-go-qa
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: simple-app-go=ghcr.io/djimenezc/devops-automation/simple-app-go:^2.0
    argocd-image-updater.argoproj.io/psplusext.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: "/environments/promotion-helm/envs/qa"
    argocd-image-updater.argoproj.io/git-branch: feature/environment-promotion
spec:
  destination:
    namespace: qa
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: git@github.com:djimenezc/devops-automation.git
    targetRevision: feature/environment-promotion
  sources:
    - chart: helm-simple-go-app
      targetRevision: 0.1.0
      repoURL: ghcr.io/djimenezc
      helm:
        valueFiles:
          - $values/environments/promotion-helm/envs/qa/settings.yaml
          - $values/environments/promotion-helm/envs/qa/version.yaml
    - repoURL: 'https://github.com/djimenezc/devops-automation'
      ref: values
      targetRevision: feature/environment-promotion

