apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: git@github.com:djimenezc/devops-automation.git
    targetRevision: helm/v0.2.3
    path: environments/promotion-helm/app
    helm:
      valueFiles:
        - envs/prod/values-settings.yaml
        - envs/prod/values-version.yaml
        - envs/prod/values-env.yaml
