apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-go-staging
  namespace: argocd
spec:
  destination:
    namespace: staging
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: git@github.com:djimenezc/devops-automation.git
    targetRevision: 3f5921edf463fe1153cda322d062fdbe97266815
    path: environments/promotion-helm/app
    helm:
      valueFiles:
        - envs/staging/values-settings.yaml
        - envs/staging/values-version.yaml
        - envs/staging/values-env.yaml
