- hosts: tag_Name_david_security_scanner
  become: true
  gather_facts: false
#  vars_files:
#    - vars.yml
  tasks:
    - name: Install dependencies
      yum:
        name: '{{ item }}'
        state: present
        update_cache: yes
      with_items:
        - git
        - vim
        - docker
        - jq
        - telnet
    - name: Start service docker if not started
      service:
        name: docker
        state: started

- hosts: tag_Name_david_security_scanner
  become: false
  become_user: ec2-user
  gather_facts: false
  tasks:
    - name: Creates directory
      file:
        path: sources
        state: directory
    - name: Download github repos
      git:
        repo: '{{ item.repo }}'
        dest: 'sources/{{ item.name }}'
        version: '{{ item.version }}'
      with_items:
        - {
            name: 'nikto',
            repo: 'https://github.com/sullo/nikto.git',
            version: 'master'
        }
        - {
            name: 'mutillidae-docker',
            repo: 'https://github.com/webpwnized/mutillidae-docker.git',
            version: '1.0.25'
        }

- hosts: tag_Name_david_security_scanner
  become: true
  gather_facts: false
  tasks:
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Install docker pip
      pip:
        name: docker
        executable: pip3

    - name: Install compose-py
      pip:
        name: docker-compose
        executable: pip3

    - name: Start mutillidae website
      community.docker.docker_compose:
        project_src: sources/mutillidae-docker
        build: no
      vars:
        ansible_python_interpreter: /bin/python3