---
# tasks file for ansible-role-podman

- name: Check if {{ podman_package_name }} is installed
  command: dpkg-query -W podman_package_name
  register: my_package_check_deb
  failed_when: my_package_check_deb.rc > 1
  changed_when: my_package_check_deb.rc == 1

- name: Creates directory
  file:
    path: "/home/{{ ansible_env.USER }}/Downloads"
    state: directory

- name: Download podman package
  get_url:
    url="{{ podman_package_url }}"
    dest="/home/{{ ansible_env.USER }}/Downloads/{{ podman_package_name }}.deb"
  when: my_package_check_deb.rc == 1

- name: Install podman 4.2.0
  become: true
  apt: deb="/home/{{ ansible_env.USER }}/Downloads/{{ podman_package_name }}.deb"
  when: my_package_check_deb.rc == 1

- name: Install buildah
  become: true
  apt:
    name: 'buildah'
    state: present

- name: Install skopeo
  become: true
  apt:
    name: 'skopeo'
    state: present

- name: Download github repos
  git:
    repo: '{{ item.repo }}'
    dest: 'sources/{{ item.name }}'
    version: '{{ item.version }}'
  with_items:
    - {
      name: 'gvisor-tap-vsock',
      repo: 'https://github.com/containers/gvisor-tap-vsock.git',
      version: 'main'
    }

- name: Build the gvisor-tap-vsock
  make:
    chdir: /home/ubuntu/sources/gvisor-tap-vsock

- name: Creates directory
  file:
    path: "/usr/local/libexec/podman"
    state: directory

- name: Copy gvproxy
  become: yes
  copy:
    src: /home/ubuntu/sources/gvisor-tap-vsock/bin/gvproxy
    dest: /usr/local/libexec/podman
    remote_src: yes
