---
# tasks file for ansible-role-podman

- name: Check if {{ podman_package_name }} is installed
  command: dpkg-query -W podman_package_name
  register: my_package_check_deb
  failed_when: my_package_check_deb.rc > 1
  changed_when: my_package_check_deb.rc == 1

- name: Creates directory
  file:
    path: "/home/{{ ansible_env.USER }}/Downloads"
    state: directory

- name: Download podman package
  get_url:
    url="{{ podman_package_url }}"
    dest="/home/{{ ansible_env.USER }}/Downloads/{{ podman_package_name }}.deb"
  when: my_package_check_deb.rc == 1

- name: Install podman 4.2.0
  apt: deb="/home/{{ ansible_env.USER }}/Downloads/{{ podman_package_name }}.deb"
  when: my_package_check_deb.rc == 1
