# .github/workflows/promote-to-production.yaml
name: Promote to production

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - run: |
          # configure git client
          git config --global user.email "djimenez@savispain.es"
          git config --global user.name "Github promoter"

          echo "Extracting version from staging file"
          cat environments/promotion-helm/gitops/staging.yaml
          version=$(cat environments/promotion-helm/gitops/staging.yaml | yq '.spec.source.targetRevision' | xargs)

          # create a new branch
          git switch -c production/${version}

          echo "Helm version to promote ${version}"
          # promote the change
          cp environments/promotion-helm/app/envs/staging/values-version.yaml environments/promotion-helm/app/envs/prod/values-version.yaml
          # promote chart version
          version="${version}" yq -i e ".spec.source.targetRevision = strenv(version)" environments/promotion-helm/gitops/production.yaml

          # push the change to the new branch
          git add environments/promotion-helm/app/envs/prod/values-version.yaml
          git add environments/promotion-helm/gitops/production.yaml
          git commit -m "Promote staging to production"

          git push -u origin production/${version}

          gh pr create \
            -B ${{ steps.extract_branch.outputs.branch }} \
            -H production/${version} \
            --title "Promote staging to production" \
            --body "Automatically created by GHA"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
