# .github/workflows/promote-to-staging.yaml
name: Promote to staging

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - run: |
          # configure git client
          git config --global user.email "djimenez@savispain.es"
          git config --global user.name "Github promoter"

          echo "Extracting version from argocd-image-updater file"
          cat environments/promotion-helm/app/.argocd-source-simple-app-go-development.yaml
          version=$(cat environments/promotion-helm/app/.argocd-source-simple-app-go-development.yaml | yq '.helm.parameters[] | select (.name == "image.tag").value' | xargs)
          echo "version to promote ${version}"

          # promote the change
#          cp environments/promotion-helm/app/dev/version.yaml environments/promotion-helm/app/staging/version.yaml
#
#          # push the change to the new branch
#          git add environments/promotion-helm/app/staging/version.yaml
#          git commit -m "Promote development to staging"
#          git push -u origin ${{ steps.extract_branch.outputs.branch }}
