# This workflow will create new version when something is pushed to master
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: release

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.2
      env:
        NODE_ENV: development
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - uses: actions/checkout@v2
      - name: Disable git hooks
        run: npm set-script prepare ''
      - name: NPM Install
        run: npm install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 16
          branches: |
            [
              'master'
            ]
      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}