name: Security Scan Full

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
      name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      url:
        description: 'Target URL'
        required: true
        type: string
        default: https://www.zapproxy.org
      name:
        description: 'Scan Id'
        required: true
        type: string
        default: capi API

jobs:

  capi_scan:
    runs-on: ubuntu-latest
    name: Scan the application ${{ inputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ZAP Scan API ${{ inputs.name }}
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ inputs.url }}
          format: openapi
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Show zap_scan.zip
        run: ls -la

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: zap_scan.zip
          if-no-files-found: error

