name: Security Scan

on:
  schedule:
    # Runs every day At 01:00.
    - cron: '0 1 * * *'
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:

  scan-zap-baseline:
    uses: ./.github/workflows/security-scan-manual.yml
    with:
      url: 'https://www.zapproxy.org'
      name: 'zapproxy'

  scan-api:
    uses: ./.github/workflows/security-scan-manual.yml
    with:
      url: 'https://zapsample.demo.community.intersystems.com/crudall/_spec'
      name: 'example-api'
      type: 'api-scan'

  scan-full:
    needs: [scan-zap-baseline]
    uses: ./.github/workflows/security-scan-manual.yml
    with:
      url: 'https://zapsample.demo.community.intersystems.com/crudall/_spec'
      name: 'example-api'
      type: 'api-scan'
      enable_ajax_spider: true
