name: Security Scan

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:

  scan-thulium:
    uses: ./.github/workflows/security-scan-manual.yml
    with:
      url: 'https://couponbeard.com/thulium'
      name: 'thulium'

  scan-couponbeard:
    uses: ./.github/workflows/security-scan-manual.yml
    with:
      url: 'https://couponbeard.com'
      name: 'couponbeard'

  scan-zap:
    uses: ./.github/workflows/security-scan-manual.yml
    with:
      url: 'https://www.zapproxy.org'
      name: 'zapproxy'
